name: Nightly

on:
  schedule:
    - cron: '0 0 * * * '

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "swift:nightly"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: swiftlang/${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Swift Build
      run: swift build -v -c debug
    - name: Swift Test
      run: swift test -v -c debug
