name: tests

on:
  - push
  - pull_request

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "swift:5.7"
          - "swift:5.8"
          - "swift:5.9"
          - "swift:5.10"
    name: Test
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Test
      uses: ./.github/workflows/swift-test.yml

  macos:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Test
      uses: ./.github/workflows/swift-test.yml
